/**
 * Pure CSV layer for the admin Units view bulk import/update flow.
 *
 * - `parseCsvText` is a small RFC 4180-ish CSV reader: handles quoted
 *   fields, doubled quotes (`""`) inside quoted fields, embedded commas
 *   and newlines inside quoted fields, CRLF line endings, blank lines,
 *   and a leading UTF-8 BOM.
 * - `formatUnitsCsv` and `unitsCsvTemplate` produce CSV text the parser
 *   can round-trip cleanly (quoting any field containing comma, quote,
 *   CR, or LF).
 * - `parseUnitsImport` validates a CSV against the current units +
 *   agents and returns a structured per-row preview the modal UI
 *   renders directly. It does NOT mutate state.
 *
 * Match rules for "is this row an update or a new unit":
 *  1. If the row's `id` matches an existing unit by id → update.
 *  2. If the row's `id` is set but no existing unit has that id → error
 *     (we deliberately do NOT silently turn it into a new row with that
 *     id, which would let typos create orphans).
 *  3. If the row's `id` is blank → fall back to matching an existing
 *     unit by exact `addressLine1 + addressLine2` (so a round-trip
 *     export → spreadsheet edit → re-import works without ids).
 *  4. Otherwise → new (a fresh `u<timestamp>` id is generated by the
 *     caller at apply-time, not here, so the parser stays pure).
 */

import type { AdminAgent, AdminUnit } from "./adminMockData";

// ─── Column contract ────────────────────────────────────────────────────────

export const UNITS_CSV_COLUMNS = [
  "id",
  "addressLine1",
  "addressLine2",
  "acType",
  "systems",
  "additional",
  "agentId",
] as const;

export type UnitsCsvColumn = (typeof UNITS_CSV_COLUMNS)[number];

const REQUIRED_COLUMNS: readonly UnitsCsvColumn[] = ["addressLine1"];

// ─── Public types ───────────────────────────────────────────────────────────

export type UnitImportStatus = "new" | "update" | "unchanged" | "error";

export type UnitDiffField = {
  field: string;
  before: string;
  after: string;
};

export type UnitImportRow = {
  /** 1-indexed row number in the source CSV (header is row 1, first
   *  data row is row 2). Used in error messages and the preview table. */
  rawRowNumber: number;
  /** The raw values keyed by column name, for display in the preview
   *  even when validation fails. */
  raw: Record<string, string>;
  status: UnitImportStatus;
  /** The validated unit. For "update" / "unchanged" this carries the
   *  matched id; for "new" the id is left empty and the apply step
   *  generates one. Absent for "error" rows. */
  parsed?: AdminUnit;
  /** The current unit this row matched (set for "update" and
   *  "unchanged"). */
  before?: AdminUnit;
  /** Field-by-field diff, only set for "update". */
  diff?: UnitDiffField[];
  /** Human-readable reasons. Empty for non-error rows. */
  errors: string[];
};

export type UnitsImportPreview = {
  rows: UnitImportRow[];
  counts: {
    new: number;
    update: number;
    unchanged: number;
    error: number;
    total: number;
  };
  /** Set when the file is so broken we couldn't even produce row data
   *  (e.g. empty input, missing header). When set, `rows` is empty. */
  fatal?: string;
};

// ─── CSV parsing primitive ─────────────────────────────────────────────────

/**
 * Split CSV text into rows of fields. Handles quoted fields, embedded
 * commas/newlines/quotes inside quotes, CRLF, blank lines, and a
 * leading UTF-8 BOM. Returns a 2D array; blank/whitespace-only rows
 * are dropped.
 */
export function parseCsvText(input: string): string[][] {
  if (!input) return [];
  let text = input;
  if (text.charCodeAt(0) === 0xfeff) text = text.slice(1);

  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let inQuotes = false;
  let i = 0;
  const n = text.length;

  while (i < n) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i += 2;
        } else {
          inQuotes = false;
          i += 1;
        }
      } else {
        field += c;
        i += 1;
      }
    } else {
      if (c === '"') {
        inQuotes = true;
        i += 1;
      } else if (c === ",") {
        row.push(field);
        field = "";
        i += 1;
      } else if (c === "\r") {
        row.push(field);
        field = "";
        rows.push(row);
        row = [];
        if (text[i + 1] === "\n") i += 2;
        else i += 1;
      } else if (c === "\n") {
        row.push(field);
        field = "";
        rows.push(row);
        row = [];
        i += 1;
      } else {
        field += c;
        i += 1;
      }
    }
  }

  // Flush the trailing field/row only if the last line wasn't a clean
  // newline. (If it was, `field === "" && row.length === 0` and we'd
  // otherwise emit a phantom row.)
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }

  // Drop fully-blank rows so a trailing newline or stray blank line
  // doesn't surface as an "error" row.
  return rows.filter((r) => r.some((f) => f.trim().length > 0));
}

// ─── CSV writing helpers ───────────────────────────────────────────────────

function escapeCsvField(value: string): string {
  if (/[",\r\n]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function unitToRow(unit: AdminUnit): readonly string[] {
  return [
    unit.id,
    unit.addressLine1,
    unit.addressLine2,
    unit.ac.type,
    String(unit.ac.systems),
    String(unit.ac.additional),
    unit.agentId ?? "",
  ];
}

/** CSV string of every supplied unit, preceded by the canonical header. */
export function formatUnitsCsv(units: readonly AdminUnit[]): string {
  const lines: string[] = [UNITS_CSV_COLUMNS.join(",")];
  for (const unit of units) {
    lines.push(unitToRow(unit).map(escapeCsvField).join(","));
  }
  return lines.join("\n") + "\n";
}

/** Empty template with the canonical header + two example rows that
 *  show both an "add new unit" row (blank id) and an "update existing
 *  unit" row (id populated). */
export function unitsCsvTemplate(): string {
  const example1: readonly string[] = [
    "",
    "10 / 25 Example Street",
    "Lot 10 · Suburb NSW 2000",
    "split",
    "2",
    "0",
    "",
  ];
  const example2: readonly string[] = [
    "u1",
    "G01 / 335 Aspen Village",
    "Lot 3 · Greenway ACT 2900",
    "ducted",
    "1",
    "1",
    "ag-001",
  ];
  return (
    UNITS_CSV_COLUMNS.join(",") +
    "\n" +
    example1.map(escapeCsvField).join(",") +
    "\n" +
    example2.map(escapeCsvField).join(",") +
    "\n"
  );
}

// ─── Import / validate ─────────────────────────────────────────────────────

function normaliseHeader(name: string): string {
  return name.trim().toLowerCase();
}

const COLUMN_LOOKUP: Record<string, UnitsCsvColumn> = (() => {
  const lookup: Record<string, UnitsCsvColumn> = {};
  for (const col of UNITS_CSV_COLUMNS) {
    lookup[normaliseHeader(col)] = col;
  }
  return lookup;
})();

function parseNonNegativeInt(
  raw: string,
  fieldLabel: string,
  errors: string[],
): number {
  const trimmed = raw.trim();
  if (trimmed === "") return 0;
  if (!/^\d+$/.test(trimmed)) {
    errors.push(
      `${fieldLabel} must be a non-negative whole number (got "${raw}").`,
    );
    return 0;
  }
  const n = Number(trimmed);
  if (!Number.isFinite(n) || n < 0) {
    errors.push(
      `${fieldLabel} must be a non-negative whole number (got "${raw}").`,
    );
    return 0;
  }
  return n;
}

function parseAcType(
  raw: string,
  errors: string[],
): AdminUnit["ac"]["type"] {
  const trimmed = raw.trim().toLowerCase();
  if (trimmed === "") return "unknown";
  if (trimmed === "split" || trimmed === "ducted" || trimmed === "unknown") {
    return trimmed;
  }
  errors.push(
    `Unknown AC type "${raw}". Use one of split, ducted, unknown (or leave blank).`,
  );
  return "unknown";
}

function unitsEqual(a: AdminUnit, b: AdminUnit): boolean {
  return (
    a.addressLine1 === b.addressLine1 &&
    a.addressLine2 === b.addressLine2 &&
    a.ac.type === b.ac.type &&
    a.ac.systems === b.ac.systems &&
    a.ac.additional === b.ac.additional &&
    a.agentId === b.agentId
  );
}

function diffUnits(before: AdminUnit, after: AdminUnit): UnitDiffField[] {
  const out: UnitDiffField[] = [];
  if (before.addressLine1 !== after.addressLine1) {
    out.push({
      field: "addressLine1",
      before: before.addressLine1,
      after: after.addressLine1,
    });
  }
  if (before.addressLine2 !== after.addressLine2) {
    out.push({
      field: "addressLine2",
      before: before.addressLine2,
      after: after.addressLine2,
    });
  }
  if (before.ac.type !== after.ac.type) {
    out.push({
      field: "acType",
      before: before.ac.type,
      after: after.ac.type,
    });
  }
  if (before.ac.systems !== after.ac.systems) {
    out.push({
      field: "systems",
      before: String(before.ac.systems),
      after: String(after.ac.systems),
    });
  }
  if (before.ac.additional !== after.ac.additional) {
    out.push({
      field: "additional",
      before: String(before.ac.additional),
      after: String(after.ac.additional),
    });
  }
  if (before.agentId !== after.agentId) {
    out.push({
      field: "agentId",
      before: before.agentId ?? "",
      after: after.agentId ?? "",
    });
  }
  return out;
}

/**
 * Validate raw CSV text against the current units + agents and return
 * the per-row preview. Pure function; never touches any state.
 */
export function parseUnitsImport(
  csvText: string,
  currentUnits: readonly AdminUnit[],
  agents: readonly AdminAgent[],
): UnitsImportPreview {
  const emptyCounts = { new: 0, update: 0, unchanged: 0, error: 0, total: 0 };
  if (!csvText || !csvText.trim()) {
    return {
      rows: [],
      counts: emptyCounts,
      fatal: "The file is empty. Paste CSV text or choose a non-empty .csv file.",
    };
  }

  const grid = parseCsvText(csvText);
  if (grid.length === 0) {
    return {
      rows: [],
      counts: emptyCounts,
      fatal: "The file has no rows. The first line should be the column headers.",
    };
  }

  const rawHeader = grid[0];
  const headerNames = rawHeader.map(normaliseHeader);
  const columnIndex = new Map<UnitsCsvColumn, number>();
  for (let i = 0; i < headerNames.length; i++) {
    const known = COLUMN_LOOKUP[headerNames[i]];
    if (known) columnIndex.set(known, i);
  }

  const missingRequired = REQUIRED_COLUMNS.filter((c) => !columnIndex.has(c));
  if (missingRequired.length > 0) {
    return {
      rows: [],
      counts: emptyCounts,
      fatal: `Missing required column${
        missingRequired.length > 1 ? "s" : ""
      }: ${missingRequired.join(", ")}. Download the template to see the expected header.`,
    };
  }

  const rows: UnitImportRow[] = [];
  // Track addresses we'd be assigning to multiple incoming rows so we
  // don't silently merge them into a single update target.
  const seenAddressKeys = new Map<string, number>();
  const seenIds = new Map<string, number>();

  for (let rowIdx = 1; rowIdx < grid.length; rowIdx++) {
    const cells = grid[rowIdx];
    const rawRowNumber = rowIdx + 1; // 1-indexed including header

    const get = (col: UnitsCsvColumn): string => {
      const idx = columnIndex.get(col);
      if (idx === undefined) return "";
      return cells[idx] ?? "";
    };

    const raw: Record<string, string> = {};
    for (const col of UNITS_CSV_COLUMNS) raw[col] = get(col);

    const errors: string[] = [];

    const idRaw = raw.id.trim();
    const addr1 = raw.addressLine1.trim();
    const addr2 = raw.addressLine2.trim();
    const agentIdRaw = raw.agentId.trim();

    if (addr1 === "") {
      errors.push("Missing addressLine1 (required).");
    }

    const acType = parseAcType(raw.acType, errors);
    const systems = parseNonNegativeInt(raw.systems, "systems", errors);
    const additional = parseNonNegativeInt(raw.additional, "additional", errors);

    let agentId: string | null = null;
    if (agentIdRaw !== "") {
      const found = agents.find((a) => a.id === agentIdRaw);
      if (!found) {
        errors.push(
          `Unknown agentId "${agentIdRaw}" — no agent with that id exists.`,
        );
      } else {
        agentId = found.id;
      }
    }

    // Match an existing unit. We do this even when other validation
    // errors exist, so the preview still says "this row was meant to
    // update unit X" rather than misleadingly showing "New".
    let before: AdminUnit | undefined;
    if (idRaw !== "") {
      const byId = currentUnits.find((u) => u.id === idRaw);
      if (byId) {
        before = byId;
      } else {
        errors.push(
          `Unknown unit id "${idRaw}" — clear the id column to add this row as a new unit.`,
        );
      }
    } else if (addr1 !== "") {
      const addressKey = `${addr1}\u0000${addr2}`;
      const byAddress = currentUnits.find(
        (u) => u.addressLine1 === addr1 && u.addressLine2 === addr2,
      );
      if (byAddress) before = byAddress;

      // Two incoming rows targeting the same address-only key would
      // both try to update the same unit — flag the duplicate so the
      // admin can fix the source CSV.
      const seenAt = seenAddressKeys.get(addressKey);
      if (seenAt !== undefined) {
        errors.push(
          `Duplicate row — addressLine1 + addressLine2 also appears on row ${seenAt}.`,
        );
      } else {
        seenAddressKeys.set(addressKey, rawRowNumber);
      }
    }

    if (idRaw !== "") {
      const seenAt = seenIds.get(idRaw);
      if (seenAt !== undefined) {
        errors.push(`Duplicate row — id "${idRaw}" also appears on row ${seenAt}.`);
      } else {
        seenIds.set(idRaw, rawRowNumber);
      }
    }

    if (errors.length > 0) {
      rows.push({
        rawRowNumber,
        raw,
        status: "error",
        before,
        errors,
      });
      continue;
    }

    // The CSV layer doesn't currently carry `buildingId` — building
    // assignment is edited per-unit in the Units view. For updates we
    // preserve the existing unit's building; for new rows we default to
    // whatever building the first existing unit lives in (a safe
    // placeholder for a mockup; the admin can re-assign from the unit
    // editor afterwards).
    const buildingId = before
      ? before.buildingId
      : (currentUnits[0]?.buildingId ?? "");

    const parsed: AdminUnit = {
      id: before ? before.id : "",
      addressLine1: addr1,
      addressLine2: addr2,
      ac: { type: acType, systems, additional },
      agentId,
      buildingId,
    };

    if (before) {
      if (unitsEqual(before, parsed)) {
        rows.push({
          rawRowNumber,
          raw,
          status: "unchanged",
          before,
          parsed,
          errors: [],
        });
      } else {
        rows.push({
          rawRowNumber,
          raw,
          status: "update",
          before,
          parsed,
          diff: diffUnits(before, parsed),
          errors: [],
        });
      }
    } else {
      rows.push({
        rawRowNumber,
        raw,
        status: "new",
        parsed,
        errors: [],
      });
    }
  }

  const counts = {
    new: rows.filter((r) => r.status === "new").length,
    update: rows.filter((r) => r.status === "update").length,
    unchanged: rows.filter((r) => r.status === "unchanged").length,
    error: rows.filter((r) => r.status === "error").length,
    total: rows.length,
  };

  return { rows, counts };
}

// ─── Apply ─────────────────────────────────────────────────────────────────

/**
 * Fold an apply-ready preview into the existing units list. Skips
 * unchanged and error rows. Generates fresh ids for `new` rows from
 * the caller-supplied `nextId` (kept injectable so tests can be
 * deterministic; the UI passes `() => \`u${Date.now()}\``).
 *
 * Returns a NEW array; never mutates the input.
 */
export function applyUnitsImport(
  currentUnits: readonly AdminUnit[],
  preview: UnitsImportPreview,
  nextId: () => string,
): AdminUnit[] {
  const next: AdminUnit[] = [...currentUnits];
  // Track ids already used during this apply pass so two "new" rows
  // applied in the same millisecond don't collide.
  const usedIds = new Set(next.map((u) => u.id));

  for (const row of preview.rows) {
    if (row.status === "update" && row.parsed) {
      const idx = next.findIndex((u) => u.id === row.parsed!.id);
      if (idx !== -1) next[idx] = row.parsed;
    } else if (row.status === "new" && row.parsed) {
      let id = nextId();
      while (usedIds.has(id)) id = `${id}-${usedIds.size + 1}`;
      usedIds.add(id);
      next.push({ ...row.parsed, id });
    }
  }

  return next;
}
