// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin/AdminApp.tsx": () => import("../components/mockups/admin/AdminApp.tsx"),
  "./components/mockups/admin/UnitsCsvImportModal.tsx": () => import("../components/mockups/admin/UnitsCsvImportModal.tsx"),
  "./components/mockups/booking-flow/BookingFlowConfirmation.tsx": () => import("../components/mockups/booking-flow/BookingFlowConfirmation.tsx"),
  "./components/mockups/booking-flow/BookingFlowDesktop.tsx": () => import("../components/mockups/booking-flow/BookingFlowDesktop.tsx"),
  "./components/mockups/booking-flow/BookingFlowMobile.tsx": () => import("../components/mockups/booking-flow/BookingFlowMobile.tsx"),
  "./components/mockups/booking-slots/SlotsDesktop.tsx": () => import("../components/mockups/booking-slots/SlotsDesktop.tsx"),
  "./components/mockups/booking-slots/SlotsMobile.tsx": () => import("../components/mockups/booking-slots/SlotsMobile.tsx"),
  "./components/mockups/booking-slots/SlotsMobileLite.tsx": () => import("../components/mockups/booking-slots/SlotsMobileLite.tsx"),
  "./components/mockups/booking-pages/AcDesktop.tsx": () => import("../components/mockups/booking-pages/AcDesktop.tsx"),
  "./components/mockups/booking-pages/AcExampleModal.tsx": () => import("../components/mockups/booking-pages/AcExampleModal.tsx"),
  "./components/mockups/booking-pages/AcMobile.tsx": () => import("../components/mockups/booking-pages/AcMobile.tsx"),
  "./components/mockups/booking-pages/AccessDesktop.tsx": () => import("../components/mockups/booking-pages/AccessDesktop.tsx"),
  "./components/mockups/booking-pages/AccessMobile.tsx": () => import("../components/mockups/booking-pages/AccessMobile.tsx"),
  "./components/mockups/booking-pages/BookerDesktop.tsx": () => import("../components/mockups/booking-pages/BookerDesktop.tsx"),
  "./components/mockups/booking-pages/BookerMobile.tsx": () => import("../components/mockups/booking-pages/BookerMobile.tsx"),
  "./components/mockups/booking-pages/PayDesktop.tsx": () => import("../components/mockups/booking-pages/PayDesktop.tsx"),
  "./components/mockups/booking-pages/PayMobile.tsx": () => import("../components/mockups/booking-pages/PayMobile.tsx"),
  "./components/mockups/booking-pages/UnitDesktop.tsx": () => import("../components/mockups/booking-pages/UnitDesktop.tsx"),
  "./components/mockups/booking-pages/UnitMobile.tsx": () => import("../components/mockups/booking-pages/UnitMobile.tsx"),
  "./components/mockups/booking-form/BookingForm.bookAnother.test.tsx": () => import("../components/mockups/booking-form/BookingForm.bookAnother.test.tsx"),
  "./components/mockups/booking-form/BookingForm.tsx": () => import("../components/mockups/booking-form/BookingForm.tsx")
};
